# symbolç”¨  ğŸ…° ğŸ…± ğŸ…² ğŸ…³ ğŸ…´ ğŸ…µ ğŸ…¶ ğŸ…· ğŸ…¸ ğŸ…¹ ğŸ…º ğŸ…» ğŸ…¼ ğŸ…½ ğŸ…¾ ğŸ…¿ ğŸ†€ ğŸ† ğŸ†‚ ğŸ†ƒ ğŸ†„ ğŸ†… ğŸ†† ğŸ†‡ ğŸ†ˆ ğŸ†‰

# ã‚¨ãƒ‡ã‚£ã‚¿ãƒ¼ã®è£œå®Œã‚’è¨­å®šã‚¹ã‚­ãƒ¼ãƒã«åˆã‚ã›ã¦å–å¾—
"$schema" = 'https://starship.rs/config-schema.json'

# ã‚·ã‚§ãƒ«ã®ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®é–“ã«ç©ºè¡Œã‚’æŒ¿å…¥ã™ã‚‹
add_newline = true

# ã‚«ã‚¹ã‚¿ãƒ ãƒ•ã‚©ãƒ¼ãƒãƒƒãƒˆã§ãƒœãƒ¼ãƒ€ãƒ¼ã‚’è¿½åŠ 
format = """
[â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€](dimmed white)
$all\
$character"""

[git_branch]
symbol = '* '

[aws]
# symbol = 'ğŸ…° '
disabled = false
format = 'on [$symbol$profile]($style) '
style = 'bold blue'

[aws.profile_aliases]
Enterprise_Naming_Scheme-voidstars = 'void**'

[gcloud]
disabled = true

[kubernetes]
format = 'on [â›µ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "ğŸ’” " },
]

# [golang]
# symbol = 'ğŸ…¶ '
# format = 'via [$symbol($version )($mod_version )]($style)'

